name: shell-command
on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run: echo "welcome"
      - name: multiline script
        run: |
           node -v
           npm -v